name: georgec
favicon: null
layout_spectrum: 0.676445676246658
typography_spectrum: 0.3314132241066545
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.4297933205962181
  lightness: 0.007499107858166099
  saturation: 0.20019418164156377
  rhythmicContrast: 0.2484346937853843
purpose: []
